package com.zeera.ui;

import java.util.List;
import com.zeera.dao.*;
import com.zeera.model.*;

public class Content {
  private String content;

 
  private static ZeeraDAO menu = new ZeeraDAOImpl();
  
  List<MenuItem> items = menu.listAllItems();
  
  
  
  public String getContent() {
	return content;
  }

  public void prepareContent() {
	  
	  content = "<body>\n"
			+ "\n"
			+ "  <section id=\"title\">\n"
			+ "    <div class=\"container-fluid\">\n"
			+ "\n"
			+ "\n"
			+ "      <nav class=\"navbar navbar-expand-lg navbar-dark\">\n"
			+ "        <a class=\"navbar-brand\" href=\"\">Zeera</a>\n"
			+ "        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
			+ "          <span class=\"navbar-toggler-icon\"></span>\n"
			+ "        </button>\n"
			+ "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
			+ "          <ul class=\"navbar-nav ml-auto\">\n"
			+ "            <li class=\"nav-item\">\n"
			+ "              <a class=\"nav-link\" href=\"#menu_card\">Menu</a>\n"
			+ "            </li>\n"
			+ "            <li class=\"nav-item\">\n"
			+ "              <a class=\"nav-link\" href=\"#speciality\">Speciality</a>\n"
			+ "            </li>\n"
			+ "            <li class=\"nav-item\">\n"
			+ "              <a class=\"nav-link\" href=\"#footer\">Contact</a>\n"
			+ "            </li>\n"
			+ "          </ul>\n"
			+ "        </div>\n"
			+ "      </nav>\n"
			+ "    </div>\n"
			+ "  </section>\n"
			+ "\n"
			+ "  <section id=\"menu_card\">\n"
			+ "\n"
			+ "    <h1 class=\"menu-text\">MENU</h1>\n"
			+ "    <div class=\"row\">\n"
			+ "\n"
			+ "\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/89kNYC4/Cappuccino.jpg\" alt=\"Cappuccino image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(0)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(0)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(0)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/BBrBrjR/Oreo-Shake.jpg\" alt=\"Oreo Shake image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(1)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(1)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(1)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/T8Ffz9W/Paneer.jpg\" alt=\"Shahi Paneer image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(10)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(10)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(10)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/Db8Gtmm/Coke.jpg\" alt=\"Coke image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(2)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(2)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(2)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/LSdkDSk/BlackTea.jpg\" alt=\"Black Tea image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(3)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(3)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(3)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/TgCmZGz/Grill.jpg\" alt=\"Grill image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(4)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(4)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(4)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/Wfx2jN2/AlFaham.jpg\" alt=\"Al-Faham image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(5)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(5)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(5)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/Bg9sf2d/PeriPeri.jpg\" alt=\"Chicken Peri Peri image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(6)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(6)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(6)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/JkqTMFy/Shawarma.jpg\" alt=\"Shawarma image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(7)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(7)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(7)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/nbQrrTx/BBQ.jpg\" alt=\"BBQ Bucket image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(8)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(8)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(8)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/g9bQsmD/Biryani.jpg\" alt=\"Chicken Biryani image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(9)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(9)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(9)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <div class=\"item-content col-lg-4 col-md-6\">\n"
			+ "        <div class=\"card\">\n"
			+ "          <img class=\"card-img-top\" src=\"https://i.ibb.co/YfhfBt1/Carrot-Halwa.jpg\" alt=\"Gajar Halwa image\">\n"
			+ "          <div class=\"card-body\">\n"
			+ "            <h2>"+getTitle(11)+"</h2>\n"
			+ "            <p class=\"card-text\">"+getDesc(11)+"</p>\n"
			+ "            <h3>&#x20B9;"+getPrice(11)+"</h3>\n"
			+ "          </div>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "    </div>\n"
			+ "  </section>\n"
			+ "\n"
			+ "  <section id=\"speciality\">\n"
			+ "    <div id=\"speciality-item\" class=\"carousel slide\" data-ride=\"false\">\n"
			+ "      <div class=\"carousel-inner\">\n"
			+ "        <div class=\"carousel-item active\">\n"
			+ "          <h2>The aromatic spices from Kozhikode that gives our Chicken Biryani and Shahi Panner a unique taste.</h2>\n"
			+ "          <img class=\"speciality-item-image\" src=\"https://i.ibb.co/18MVqM3/Spices.jpg\" alt=\"spices image\">\n"
			+ "          <em>Kozhikode, Kerela</em>\n"
			+ "        </div>\n"
			+ "        <div class=\"carousel-item\">\n"
			+ "          <h2 class=\"speciality-text\">The fruity, floral, and incredible tasting coffee beans from Coorg that makes our coffee world class.</h2>\n"
			+ "          <img class=\"speciality-item-image\" src=\"https://i.ibb.co/j44vfmL/Coffee.jpg\" alt=\"coffee images\">\n"
			+ "          <em>Coorg, Karntaka</em>\n"
			+ "        </div>\n"
			+ "        <div class=\"carousel-item\">\n"
			+ "          <h2 class=\"speciality-text\">Gajar Halwa made up from the best and tastiest red carrots of Lakhenpur.</h2>\n"
			+ "          <img class=\"speciality-item-image\" src=\"https://i.ibb.co/Yf4ncnn/Carrot.jpg\" alt=\"carrot image\">\n"
			+ "          <em>Lakhenpur, Kashmir</em>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "      <a class=\"carousel-control-prev\" href=\"#speciality-item\" role=\"button\" data-slide=\"prev\">\n"
			+ "        <span class=\"carousel-control-prev-icon\"></span>\n"
			+ "      </a>\n"
			+ "      <a class=\"carousel-control-next\" href=\"#speciality-item\" role=\"button\" data-slide=\"next\">\n"
			+ "        <span class=\"carousel-control-next-icon\"></span>\n"
			+ "      </a>\n"
			+ "    </div>\n"
			+ "  </section>";
 }
  
  private String getTitle(int i) {
	  return items.get(i).getMenu_item_title();
  }
  

  private String getDesc(int i) {
	  return items.get(i).getMenu_item_description();
  }
  
  private int getPrice(int i) {
	  return items.get(i).getMenu_item_price();
  }
}
