package com.zeera.ui;

public class Header {
  private String header;

public String getHeader() {
	return header;
}

 public void prepareHeader() {
	header = "<!DOCTYPE html>\n"
			+ "<html lang=\"en\" dir=\"ltr\">\n"
			+ "\n"
			+ "<head>\n"
			+ "  <meta charset=\"utf-8\">\n"
			+ "  <title>menu</title>\n"
			+ "  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n"
			+ " <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap\" rel=\"stylesheet\">\n"
			+ "  <link href=\"https://fonts.googleapis.com/css2?family=Pacifico&family=Permanent+Marker&display=swap\" rel=\"stylesheet\">\n"
			+ "  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n"
			+ "  <script src=\"https://kit.fontawesome.com/f4dadb4389.js\" crossorigin=\"anonymous\"></script>\n"
			+ "  <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n"
			+ "  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n"
			+ "  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n"
			+ "\n"
			+ "<style media=\"screen\">\n"
			+ "#title{\n"
			+ "  background-color: #f08768;\n"
			+ "  color: #fff;\n"
			+ "}\n"
			+ "#title .container-fluid{\n"
			+ "  padding-right: 0;\n"
			+ "}\n"
			+ ".navbar-brand{\n"
			+ "  font-family: 'Permanent Marker', cursive;\n"
			+ "  font-size: 2.5rem;\n"
			+ "  font-weight: bold;\n"
			+ "}\n"
			+ ".nav-item{\n"
			+ "  padding: 0 18px;\n"
			+ "}\n"
			+ ".nav-link{\n"
			+ "  font-size: 2rem;\n"
			+ "  font-family: 'Stencil Std';\n"
			+ "  font-weight: bold;\n"
			+ "  color: #fff;\n"
			+ "}\n"
			+ "\n"
			+ "#menu_card{\n"
			+ "  padding: 100px;\n"
			+ "  padding-top: 20px;\n"
			+ "  text-align: center;\n"
			+ "  background-color: #fff;\n"
			+ "}\n"
			+ ".menu-text{\n"
			+ "  font-family: 'Permanent Marker', cursive;\n"
			+ "}\n"
			+ ".card{\n"
			+ "  border-radius: 10%;\n"
			+ "box-shadow: 0 4px 12px 12px rgba(0, 0, 0, 0.2), 0 6px 20px 0px rgba(0, 0, 0, 0.19);"
			+ "}\n"
			+ ".card-img-top{\n"
			+ "  height: 225px;\n"
			+ "  width: 100%;\n"
			+ "  border-radius: 10% 10% 0 0;\n"
			+ "}\n"
			+ ".item-content{\n"
			+ "  padding: 3% 2%;\n"
			+ "}\n"
			+ ".container-fluid{\n"
			+ "  padding: 1% 15% 2%;\n"
			+ "}\n"
			+ "#speciality{\n"
			+ "  text-align: center;\n"
			+ "  background-color: #f08768;\n"
			+ "  color: #fff;\n"
			+ "}\n"
			+ ".speciality-item-image{\n"
			+ "  width: 10%;\n"
			+ "  border-radius: 100%;\n"
			+ "  margin: 20px;\n"
			+ "}\n"
			+ ".carousel-item{\n"
			+ "  padding: 7% 15%;\n"
			+ "}\n"
			+ "#footer{\n"
			+ "  text-align: center;\n"
			+ "  padding: 7% 15%;\n"
			+ "  background-color: #dfe6d8;\n"
			+ "}\n"
			+ ".icons{\n"
			+ "  margin: 20px 10px;\n"
			+ "}\n"
			+ ".fa-twitter:hover{\n"
			+ "  color: #3cbefa;\n"
			+ "}\n"
			+ ".fa-facebook-f:hover{\n"
			+ "  color: #0048f0;\n"
			+ "}\n"
			+ ".fa-instagram:hover{\n"
			+ "  color: #eb2fb9;\n"
			+ "}\n"
			+ ".fa-envelope:hover{\n"
			+ "  color: #eb1010;\n"
			+ "}\n"
            +".black{\n"
            + "	color:black;\n"
            + "}"
			+ "</style>\n"
			+ "\n"
			+ "</head>";
 }
  
  
}
